"""Kali browser acceptance against an isolated DB, never a real target."""
from pathlib import Path
import json
import os
from time import time
TITLE="持久化浏览器验收-"+str(int(time()))
from playwright.sync_api import sync_playwright, expect

BASE=os.environ.get("CAIRN_RESEARCH_QA_URL","http://192.168.61.129:8012")
OUT=Path("/tmp/cairn-research-integration-qa")
OUT.mkdir(exist_ok=True)
fixture=Path("/tmp/cairn-research-material-fixture")
fixture.mkdir(exist_ok=True)
(fixture/"sample.txt").write_text("Browser acceptance material; no target execution.\n")
checks=[]; errors=[]
with sync_playwright() as p:
    browser=p.chromium.launch(headless=True)
    page=browser.new_page(viewport={"width":1440,"height":1000})
    page.on("pageerror",lambda e:errors.append(str(e)))
    page.goto(BASE+"/research")
    expect(page.get_by_test_id("new-project")).to_be_visible()
    expect(page.locator(".local-connection")).to_contain_text("研究执行器尚未接入")
    page.get_by_test_id("new-project").click()
    page.locator('[x-model="draft.title"]').fill(TITLE)
    page.locator('[x-model="draft.objective"]').fill("检查网页操作与持久记录一致；不执行目标测试。")
    page.get_by_role("textbox",name="网站或运行环境",exact=True).fill("http://example.test")
    page.get_by_role("textbox",name="代码目录或仓库",exact=True).fill(str(fixture))
    page.locator('[x-model="draft.authorized"]').check()
    page.get_by_role("button",name="授权并开始研究").click()
    expect(page.locator(".project-title h1")).to_have_text(TITLE)
    expect(page.locator(".run-banner")).to_contain_text("项目已保存，执行器尚未就绪")
    expect(page.locator(".mode-badge")).to_have_text("黑白盒联动")
    session_id=page.url.split("#/")[1]
    data=page.request.get(BASE+"/api/research/sessions/"+session_id).json()
    assert data["authorization"]["revision"]==1 and not data["findings"]
    checks.append("create persists authorization and materials without fabricated results")
    page.reload()
    expect(page.locator(".project-title h1")).to_have_text(TITLE)
    assert page.url.endswith("#/"+session_id)
    checks.append("reload restores same project and deep link")
    page.get_by_test_id("pause").click()
    expect(page.locator(".run-banner")).to_contain_text("研究已暂停")
    page.get_by_test_id("pause").click()
    expect(page.locator(".run-banner")).to_contain_text("项目已保存，执行器尚未就绪")
    assert page.locator("dialog[open]").count()==0
    after=page.request.get(BASE+"/api/research/sessions/"+session_id).json()
    assert after["authorization"]==data["authorization"] and after["usage"]==data["usage"]
    checks.append("pause/resume persists and retains authorization and usage")
    page.get_by_role("textbox",name="补充研究方向",exact=True).fill("优先检查资料来源；本条只验收 Hint 保存。")
    page.get_by_role("button",name="发送研究方向",exact=True).click()
    expect(page.locator(".next-direction")).to_contain_text("Hint 保存")
    page.reload()
    expect(page.locator(".next-direction")).to_contain_text("Hint 保存")
    checks.append("human direction persists as event and next direction")
    page.get_by_test_id("pause").click()
    expect(page.locator(".run-banner")).to_contain_text("研究已暂停")
    page.locator(".scope-button").click()
    page.get_by_text("追加或更改研究材料",exact=True).click()
    page.get_by_role("textbox",name="更新运行环境").fill("")
    page.locator('[x-model="scopeDraft.authorized"]').check()
    page.get_by_role("button",name="保存材料变更").click()
    expect(page.locator("#scope-dialog")).not_to_be_visible()
    expect(page.locator(".mode-badge")).to_have_text("代码审计")
    data=page.request.get(BASE+"/api/research/sessions/"+session_id).json()
    assert data["authorization"]["revision"]==2 and data["url"] is None
    checks.append("material update persists new scope while retaining history")
    page.get_by_test_id("report").click()
    page.get_by_test_id("generate-report").click()
    with page.expect_download() as download:
        page.get_by_role("button",name="导出 Markdown",exact=True).click()
    download.value.save_as(str(OUT/"report.md"))
    report=(OUT/"report.md").read_text()
    assert TITLE in report
    page.get_by_role("button",name="结束本轮研究",exact=True).click()
    expect(page.locator(".report-status")).to_contain_text("已暂停")
    expect(page.locator("#report-dialog .snapshot-notice")).to_be_visible()
    page.get_by_role("button",name="生成最新快照",exact=True).click()
    expect(page.locator(".report-status")).to_contain_text("已结束")
    page.get_by_role("button",name="关闭研究报告",exact=True).click()
    page.get_by_test_id("pause").click()
    expect(page.locator(".run-banner")).to_contain_text("项目已保存，执行器尚未就绪")
    checks.append("saved report download, completion and continued exploration")
    page.screenshot(path=str(OUT/"desktop.png"),full_page=True)
    assert not page.evaluate("document.documentElement.scrollWidth>innerWidth")
    page.set_viewport_size({"width":390,"height":844})
    page.get_by_role("button",name="打开项目列表").click()
    expect(page.locator(".sidebar")).to_have_class("sidebar mobile-visible")
    page.get_by_role("button",name=TITLE,exact=False).click()
    expect(page.locator(".sidebar")).not_to_have_class("sidebar mobile-visible")
    assert not page.evaluate("document.documentElement.scrollWidth>innerWidth")
    page.screenshot(path=str(OUT/"mobile.png"),full_page=True)
    checks.append("desktop and narrow viewport navigation without overflow")
    page.set_viewport_size({"width":1440,"height":1000})
    page.goto(BASE+"/")
    expect(page.locator('a[href="/research"]')).to_be_visible()
    page.locator('a[href="/research"]').click()
    expect(page.get_by_test_id("new-project")).to_be_visible()
    checks.append("original Cairn page links to integrated same-app research")
    assert not errors,errors
    (OUT/"results.json").write_text(json.dumps({"checks":checks,"errors":errors,"session_id":session_id},ensure_ascii=False,indent=2))
    browser.close()
print(json.dumps({"checks":checks,"errors":errors},ensure_ascii=False))
