"""Snapshot comparison acceptance; temporary text only, no code/model/target execution."""
import json
import tempfile
from pathlib import Path
from playwright.sync_api import sync_playwright,expect

BASE="http://192.168.61.129:8012"
OUT=Path("/tmp/cairn-research-integration-qa")
OUT.mkdir(exist_ok=True)
repo=Path(tempfile.mkdtemp(prefix="cairn-compare-ui-"))
(repo/"changed.py").write_bytes(b'header\nold line\n<b>literal fixture</b>\n')
(repo/"missing.txt").write_text("only in first snapshot\n")
(repo/"stable.txt").write_text("same text\n")
(repo/"endings.txt").write_bytes(b'same text\r\n')
(repo/"large.txt").write_text("old\n"*2000)
checks=[];errors=[]
with sync_playwright() as p:
 browser=p.chromium.launch(headless=True)
 page=browser.new_page(viewport={"width":1440,"height":1000})
 page.on("pageerror",lambda e:errors.append(str(e)))
 response=page.request.post(BASE+"/api/research/sessions",data={"title":"版本对照夹具 "+repo.name,"objective":"检查已保存文本版本对照与原证据上下文。","repo":str(repo),"authorization_confirmed":True})
 assert response.status==201,response.text()
 sid=response.json()["id"];endpoint=BASE+"/api/research/sessions/"+sid
 r=page.request.post(endpoint+"/sources",data={});assert r.status==201,r.text()
 before=r.json()
 r=page.request.post(endpoint+"/sources/"+before["id"]+"/evidence",data={"path":"changed.py","start_line":2,"end_line":3});assert r.status==201,r.text()
 eid=r.json()["evidence_id"]
 (repo/"changed.py").write_bytes(b'header\nnew line\n<b>literal fixture</b>\n')
 (repo/"missing.txt").unlink()
 (repo/"new.txt").write_text("only in second snapshot\n")
 (repo/"endings.txt").write_bytes(b'same text\n')
 (repo/"large.txt").write_text("new\n"*2000)
 r=page.request.post(endpoint+"/sources",data={});assert r.status==201,r.text()
 after=r.json()
 initial=page.request.get(endpoint).json()
 page.goto(BASE+"/research#/"+sid)
 page.get_by_role("tab",name="研究材料",exact=False).click()
 page.get_by_test_id("source-browser").click()
 page.get_by_test_id("compare-sources").click()
 dialog=page.locator("#comparison-dialog")
 expect(dialog.get_by_label("基准版本",exact=True)).to_have_value(before["id"])
 expect(dialog.get_by_label("对照版本",exact=True)).to_have_value(after["id"])
 expect(dialog.locator(".comparison-counts")).to_contain_text("3 内容变化")
 expect(dialog.locator(".comparison-counts")).to_contain_text("1 仅对照版本有")
 expect(dialog.locator(".comparison-counts")).to_contain_text("1 仅基准版本有")
 expect(dialog.locator(".comparison-counts")).to_contain_text("1 内容相同")
 dialog.locator('button[title="changed.py"]').click()
 expect(dialog.locator(".diff-line.removed")).to_contain_text("old line")
 expect(dialog.locator(".diff-line.added")).to_contain_text("new line")
 expect(dialog.locator(".comparison-diff")).to_contain_text("<b>literal fixture</b>")
 assert dialog.locator(".comparison-diff b").count()==0
 page.screenshot(path=str(OUT/"comparison-desktop.png"),full_page=True)
 checks.append("snapshot selection, change counts and literal unified diff with both line numbers")
 dialog.get_by_role("button",name="交换对照方向").click()
 expect(dialog.locator(".diff-line.removed")).to_contain_text("new line")
 expect(dialog.locator(".diff-line.added")).to_contain_text("old line")
 dialog.get_by_role("button",name="交换对照方向").click()
 expect(dialog.locator(".diff-line.added")).to_contain_text("new line")
 dialog.locator('button[title="endings.txt"]').click()
 expect(dialog.locator(".diff-line.removed .diff-eol")).to_have_text("CRLF")
 expect(dialog.locator(".diff-line.added .diff-eol")).to_have_text("LF")
 checks.append("direction swap reverses changes and newline-only differences remain visible")
 dialog.locator('button[title="large.txt"]').click()
 expect(dialog.locator(".comparison-note").filter(has_text="未完整展开")).to_be_visible()
 dialog.get_by_role("button",name="查看基准文件").click()
 expect(page.locator("#source-dialog")).to_be_visible()
 expect(page.locator("#source-dialog .code-file")).to_contain_text("large.txt")
 expect(page.locator("#source-dialog .source-code-block")).to_contain_text("old")
 page.get_by_test_id("compare-sources").click()
 expect(dialog).to_be_visible()
 dialog.get_by_label("基准版本",exact=True).select_option(before["id"])
 dialog.get_by_label("对照版本",exact=True).select_option(after["id"])
 expect(dialog.locator(".comparison-counts")).to_contain_text("3 内容变化")
 dialog.locator('button[title="new.txt"]').click()
 expect(dialog.get_by_role("button",name="查看基准文件")).to_be_disabled()
 expect(dialog.get_by_role("button",name="查看对照文件")).to_be_enabled()
 checks.append("bounded diff explicitly explains omissions; links open saved original sides")
 page.set_viewport_size({"width":390,"height":844})
 assert not page.evaluate("document.documentElement.scrollWidth>innerWidth")
 box=dialog.bounding_box();assert box["x"]>=0 and box["x"]+box["width"]<=391
 page.screenshot(path=str(OUT/"comparison-mobile.png"),full_page=True)
 dialog.get_by_label("对照版本",exact=True).select_option(before["id"])
 expect(dialog.locator(".comparison-empty")).to_be_visible()
 expect(dialog.locator(".comparison-counts")).to_contain_text("5 内容相同")
 checks.append("narrow viewport and identical-snapshot empty state")
 # Hold an actual response, change selections, then release the old response.
 page.set_viewport_size({"width":1440,"height":1000})
 response_data=page.request.get(endpoint+"/source-comparison",params={"before":before["id"],"after":after["id"]}).text()
 pending=[]
 def defer_once(route):
  pending.append(route)
 page.route("**/source-comparison?*",defer_once,times=1)
 dialog.get_by_label("对照版本",exact=True).select_option(after["id"])
 expect(dialog.get_by_role("status")).to_be_visible()
 dialog.get_by_label("对照版本",exact=True).select_option(before["id"])
 expect(dialog.locator(".comparison-empty")).to_be_visible()
 assert pending
 pending[0].fulfill(status=200,content_type="application/json",body=response_data)
 # Let the fulfilled fetch settle without sleeping.
 page.evaluate("()=>new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve)))")
 expect(dialog.locator(".comparison-empty")).to_be_visible()
 expect(dialog.get_by_label("对照版本",exact=True)).to_have_value(before["id"])
 checks.append("late response cannot replace the newly selected snapshot pair")

 dialog.get_by_role("button",name="关闭版本对照").click()
 page.set_viewport_size({"width":1440,"height":1000})
 page.get_by_role("tab",name="研究过程",exact=True).click()
 # Follow the actual saved source event link.
 page.get_by_role("button",name="查看证据 · "+eid[:8],exact=True).click()
 page.get_by_role("button",name="查看原快照与代码上下文",exact=True).click()
 expect(page.locator("#source-dialog")).to_be_visible()
 expect(page.get_by_label("源码快照版本")).to_have_value(before["id"])
 expect(page.locator("#source-dialog .source-code-block")).to_contain_text("old line")
 expect(page.get_by_label("代码起始行")).to_have_value("2")
 expect(page.get_by_label("代码结束行")).to_have_value("3")
 checks.append("existing evidence returns to exact old snapshot, file and line range")
 page.route(endpoint+"/sources/"+after["id"],lambda route:route.fulfill(status=404,content_type="application/json",body='{"detail":"验收夹具：该快照暂不可用"}'),times=1)
 page.get_by_label("源码快照版本").select_option(after["id"])
 expect(page.locator("#source-dialog .form-error")).to_contain_text("该快照暂不可用")
 expect(page.locator("#source-dialog .source-code-block")).to_have_count(0)
 checks.append("failed source lookup clears previous content instead of presenting it as evidence context")

 final=page.request.get(endpoint).json()
 assert initial==final,"Read-only comparison must not change session or evidence"
 assert not errors,errors
 (OUT/"comparison-results.json").write_text(json.dumps({"checks":checks,"errors":errors,"session_id":sid},ensure_ascii=False,indent=2))
 browser.close()
print(json.dumps({"checks":checks,"errors":errors},ensure_ascii=False))
