
from pathlib import Path
import json
from playwright.sync_api import sync_playwright, expect

BASE="http://192.168.61.129:8011/"
OUT=Path("/tmp/cairn-workbench-qa")
OUT.mkdir(exist_ok=True)
with sync_playwright() as p:
    browser=p.chromium.launch(headless=True)
    page=browser.new_page(viewport={"width":1440,"height":1000},device_scale_factor=1)
    errors=[]; external=[]; checks=[]
    page.on("pageerror",lambda e:errors.append(str(e)))
    page.on("request",lambda r:external.append(r.url) if not r.url.startswith(BASE) else None)
    page.goto(BASE)
    expect(page.locator("h1")).to_have_text("Atlas Notes")
    expect(page.locator(".evidence-title h2")).to_be_visible()
    assert not page.evaluate("document.documentElement.scrollWidth>innerWidth")
    page.screenshot(path=str(OUT/"desktop.png"),full_page=True)
    checks.append("desktop loads without overflow")
    page.get_by_role("tab",name="关联源码",exact=True).click()
    expect(page.locator(".code-file")).to_contain_text("notes.py")
    expect(page.locator(".code-line.highlight")).to_have_count(2)
    page.screenshot(path=str(OUT/"code.png"))
    page.get_by_role("tab",name="请求对照",exact=True).click()
    expect(page.locator(".http-code.variant")).to_contain_text("member-b")
    page.screenshot(path=str(OUT/"requests.png"))
    checks.append("finding -> source and HTTP evidence")
    page.get_by_test_id("pause").click()
    expect(page.get_by_test_id("pause")).to_contain_text("继续研究")
    expect(page.locator(".run-banner")).to_contain_text("研究已暂停")
    assert page.locator("dialog[open]").count()==0
    page.get_by_test_id("pause").click()
    expect(page.get_by_test_id("pause")).to_contain_text("暂停")
    checks.append("pause and resume without authorization dialog")
    page.get_by_role("textbox",name="补充研究方向",exact=True).fill("优先研究分享链接的过期边界")
    page.get_by_role("button",name="发送研究方向",exact=True).click()
    expect(page.locator(".next-direction")).to_contain_text("分享链接")
    checks.append("hint updates event stream and next direction")
    page.get_by_role("tab",name="发现",exact=False).click()
    page.locator(".filter-row").get_by_role("button",name="已排除",exact=True).click()
    expect(page.locator(".finding-card")).to_have_count(1)
    page.locator(".finding-card").click()
    expect(page.locator(".evidence-title")).to_contain_text("搜索接口")
    checks.append("finding verdict filter and evidence selection")
    page.get_by_role("tab",name="研究材料",exact=False).click()
    page.get_by_role("textbox",name="搜索研究材料",exact=True).fill("attachments")
    expect(page.locator(".asset-list>button")).to_have_count(1)
    page.locator(".asset-list>button").click()
    expect(page.locator(".code-file")).to_contain_text("attachments.py")
    checks.append("material search and source navigation")
    page.get_by_role("button",name="Harbor Web",exact=False).click()
    expect(page.locator("h1")).to_have_text("Harbor Web")
    expect(page.get_by_role("tab",name="关联源码",exact=True)).not_to_be_visible()
    page.get_by_role("button",name="Ledger Service",exact=False).click()
    expect(page.get_by_role("tab",name="请求对照",exact=True)).not_to_be_visible()
    expect(page.locator(".evidence-title")).to_contain_text("未动态验证")
    checks.append("web-only hides code and code-only hides HTTP")
    page.get_by_role("button",name="Atlas Notes",exact=False).click()
    page.get_by_test_id("retest").click()
    expect(page.get_by_test_id("retest")).to_contain_text("演示复测",timeout=5000)
    expect(page.locator(".timeline")).to_contain_text("复测演示已记录")
    page.get_by_test_id("advance").click()
    expect(page.locator(".run-banner")).to_contain_text("本轮研究已收束")
    checks.append("explicit simulated retest and completion")
    page.get_by_test_id("report").click()
    expect(page.locator("#report-dialog")).to_be_visible()
    with page.expect_download() as download:
        page.get_by_role("button",name="导出 Markdown",exact=True).click()
    download.value.save_as(str(OUT/"report.md"))
    report=(OUT/"report.md").read_text()
    assert "\n## 研究目标\n" in report and "E-007" in report and "虚构演示" in report
    assert "GET /api/notes/42" in report and "notes.py" in report
    page.keyboard.press("Escape")
    checks.append("Markdown download includes evidence, source and limitations")
    page.get_by_test_id("new-project").click()
    expect(page.locator("#create-dialog")).to_be_visible()
    page.screenshot(path=str(OUT/"create.png"))
    page.get_by_label("研究名称",exact=True).fill("我的代码项目")
    page.get_by_label("你想弄清什么？",exact=True).fill("检查接口权限")
    page.get_by_role("textbox",name="代码目录或仓库",exact=True).fill("/home/kali/labs/demo-repo")
    expect(page.locator(".auto-mode")).to_contain_text("代码审计")
    page.locator(".consent input").check()
    page.get_by_role("button",name="授权并开始研究",exact=True).click()
    expect(page.locator("h1")).to_have_text("我的代码项目")
    expect(page.locator(".evidence-empty")).to_be_visible()
    expect(page.locator(".material-row")).to_contain_text("代码审计")
    assert page.locator(".evidence-title").count()==0
    checks.append("single-authorization creation; no fabricated findings/language")
    page.get_by_role("button",name="重置演示",exact=True).click()
    expect(page.locator("h1")).to_have_text("Atlas Notes")
    assert page.locator(".project-nav>button").count()==3
    checks.append("reset removes temporary prototype input")
    page.set_viewport_size({"width":860,"height":1000})
    page.get_by_role("tab",name="发现",exact=False).click()
    page.locator(".finding-card").first.click()
    expect(page.locator(".evidence-mobile-open")).to_be_visible()
    page.get_by_role("tab",name="关联源码",exact=True).click()
    expect(page.locator(".evidence-mobile-open")).to_be_visible()
    page.screenshot(path=str(OUT/"drawer.png"),full_page=True)
    page.get_by_role("button",name="关闭证据侧栏",exact=True).click(position={"x":50,"y":350})
    expect(page.locator(".evidence-pane")).not_to_be_visible()
    expect(page.locator("h1")).to_have_text("Atlas Notes")
    page.locator(".finding-card").first.click()
    page.keyboard.press("Escape")
    expect(page.locator(".evidence-pane")).not_to_be_visible()
    page.set_viewport_size({"width":1440,"height":1000})
    page.locator(".finding-card").first.click()
    expect(page.locator(".evidence-pane")).to_be_visible()
    expect(page.locator(".evidence-backdrop")).not_to_be_visible()
    page.get_by_role("tab",name="研究过程",exact=True).click()
    checks.append("860px outside click and Escape close drawer; inside click stays; desktop remains inline")
    page.set_viewport_size({"width":390,"height":844})
    assert not page.evaluate("document.documentElement.scrollWidth>innerWidth")
    page.screenshot(path=str(OUT/"mobile.png"),full_page=True)
    page.get_by_role("tab",name="发现",exact=False).click()
    page.locator(".finding-card").first.click()
    expect(page.locator(".evidence-mobile-open")).to_be_visible()
    page.screenshot(path=str(OUT/"mobile-evidence.png"),full_page=True)
    page.get_by_role("button",name="返回研究",exact=True).click()
    expect(page.locator(".evidence-pane")).not_to_be_visible()
    page.get_by_role("button",name="打开项目列表",exact=True).click()
    page.get_by_test_id("new-project").click()
    expect(page.locator("#create-dialog")).to_be_visible()
    assert not page.evaluate("document.documentElement.scrollWidth>innerWidth")
    page.screenshot(path=str(OUT/"mobile-create.png"),full_page=True)
    page.keyboard.press("Escape")
    checks.append("390px navigation, evidence overlay and create dialog")
    assert not errors, errors
    assert not external, external
    result={"passed":len(checks),"checks":checks,"browser":"Chromium on Kali","page_errors":errors,"external_requests":external}
    (OUT/"results.json").write_text(json.dumps(result,ensure_ascii=False,indent=2)+"\n")
    print(json.dumps(result,ensure_ascii=False))
    browser.close()
